<?php
/**
 * Campaign
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Yahoo!広告 検索広告 API リファレンス / Yahoo! JAPAN Ads Search Ads API Reference
 *
 * <div lang=\"ja\">Yahoo!広告 検索広告 APIのWebサービスについて説明します。</div> <div lang=\"en\">Search Ads API Web Services supported in Yahoo! JAPAN Ads API.</div> <div><a target=\"_blank\" href=\"https://github.com/yahoojp-marketing/ads-search-api-documents/blob/master/design/v9/Route.yaml\">OpenAPI Specification</a></div> <div lang=\"ja\"><a target=\"_blank\" href=\"https://github.com/yahoojp-marketing/ads-search-api-documents/blob/master/bestpractice/ja\">Best Practice</a></div> <div lang=\"en\"><a target=\"_blank\" href=\"https://github.com/yahoojp-marketing/ads-search-api-documents/blob/master/bestpractice/en\">Best Practice</a></div>
 *
 * The version of the OpenAPI document: v9
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.2.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

use \ArrayAccess;
use \OpenAPI\Client\ObjectSerializer;

/**
 * Campaign Class Doc Comment
 *
 * @category Class
 * @description &lt;div lang&#x3D;\&quot;ja\&quot;&gt;Campaignオブジェクトは、キャンペーンの情報を表します。&lt;/div&gt; &lt;div lang&#x3D;\&quot;en\&quot;&gt;Campaign object describes Campaign information.&lt;/div&gt;
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class Campaign implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'Campaign';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'account_id' => 'int',
        'app_id' => 'string',
        'app_store' => '\OpenAPI\Client\Model\CampaignServiceAppStore',
        'bidding_strategy_configuration' => '\OpenAPI\Client\Model\CampaignServiceBiddingStrategy',
        'bidding_strategy_failed_reason' => '\OpenAPI\Client\Model\CampaignServiceBiddingStrategyFailedReason',
        'budget' => '\OpenAPI\Client\Model\CampaignServiceBudget',
        'campaign_id' => 'int',
        'campaign_name' => 'string',
        'campaign_track_id' => 'int',
        'conversion_optimizer_eligibility' => '\OpenAPI\Client\Model\CampaignServiceConversionOptimizerEligibility',
        'custom_parameters' => '\OpenAPI\Client\Model\CampaignServiceCustomParameters',
        'end_date' => 'string',
        'failed_bidding_strategy_configuration' => '\OpenAPI\Client\Model\CampaignServiceBiddingStrategy',
        'labels' => '\OpenAPI\Client\Model\CampaignServiceLabel[]',
        'serving_status' => '\OpenAPI\Client\Model\CampaignServiceServingStatus',
        'settings' => '\OpenAPI\Client\Model\CampaignServiceSettings[]',
        'start_date' => 'string',
        'tracking_url' => 'string',
        'type' => '\OpenAPI\Client\Model\CampaignServiceType',
        'url_review_data' => '\OpenAPI\Client\Model\CampaignServiceUrlReviewData',
        'user_status' => '\OpenAPI\Client\Model\CampaignServiceUserStatus',
        'created_date' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'account_id' => 'int64',
        'app_id' => null,
        'app_store' => null,
        'bidding_strategy_configuration' => null,
        'bidding_strategy_failed_reason' => null,
        'budget' => null,
        'campaign_id' => 'int64',
        'campaign_name' => null,
        'campaign_track_id' => 'int64',
        'conversion_optimizer_eligibility' => null,
        'custom_parameters' => null,
        'end_date' => null,
        'failed_bidding_strategy_configuration' => null,
        'labels' => null,
        'serving_status' => null,
        'settings' => null,
        'start_date' => null,
        'tracking_url' => null,
        'type' => null,
        'url_review_data' => null,
        'user_status' => null,
        'created_date' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'account_id' => true,
		'app_id' => true,
		'app_store' => true,
		'bidding_strategy_configuration' => true,
		'bidding_strategy_failed_reason' => true,
		'budget' => true,
		'campaign_id' => true,
		'campaign_name' => true,
		'campaign_track_id' => true,
		'conversion_optimizer_eligibility' => true,
		'custom_parameters' => true,
		'end_date' => true,
		'failed_bidding_strategy_configuration' => true,
		'labels' => true,
		'serving_status' => true,
		'settings' => true,
		'start_date' => true,
		'tracking_url' => true,
		'type' => true,
		'url_review_data' => true,
		'user_status' => true,
		'created_date' => true
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'account_id' => 'accountId',
        'app_id' => 'appId',
        'app_store' => 'appStore',
        'bidding_strategy_configuration' => 'biddingStrategyConfiguration',
        'bidding_strategy_failed_reason' => 'biddingStrategyFailedReason',
        'budget' => 'budget',
        'campaign_id' => 'campaignId',
        'campaign_name' => 'campaignName',
        'campaign_track_id' => 'campaignTrackId',
        'conversion_optimizer_eligibility' => 'conversionOptimizerEligibility',
        'custom_parameters' => 'customParameters',
        'end_date' => 'endDate',
        'failed_bidding_strategy_configuration' => 'failedBiddingStrategyConfiguration',
        'labels' => 'labels',
        'serving_status' => 'servingStatus',
        'settings' => 'settings',
        'start_date' => 'startDate',
        'tracking_url' => 'trackingUrl',
        'type' => 'type',
        'url_review_data' => 'urlReviewData',
        'user_status' => 'userStatus',
        'created_date' => 'createdDate'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'account_id' => 'setAccountId',
        'app_id' => 'setAppId',
        'app_store' => 'setAppStore',
        'bidding_strategy_configuration' => 'setBiddingStrategyConfiguration',
        'bidding_strategy_failed_reason' => 'setBiddingStrategyFailedReason',
        'budget' => 'setBudget',
        'campaign_id' => 'setCampaignId',
        'campaign_name' => 'setCampaignName',
        'campaign_track_id' => 'setCampaignTrackId',
        'conversion_optimizer_eligibility' => 'setConversionOptimizerEligibility',
        'custom_parameters' => 'setCustomParameters',
        'end_date' => 'setEndDate',
        'failed_bidding_strategy_configuration' => 'setFailedBiddingStrategyConfiguration',
        'labels' => 'setLabels',
        'serving_status' => 'setServingStatus',
        'settings' => 'setSettings',
        'start_date' => 'setStartDate',
        'tracking_url' => 'setTrackingUrl',
        'type' => 'setType',
        'url_review_data' => 'setUrlReviewData',
        'user_status' => 'setUserStatus',
        'created_date' => 'setCreatedDate'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'account_id' => 'getAccountId',
        'app_id' => 'getAppId',
        'app_store' => 'getAppStore',
        'bidding_strategy_configuration' => 'getBiddingStrategyConfiguration',
        'bidding_strategy_failed_reason' => 'getBiddingStrategyFailedReason',
        'budget' => 'getBudget',
        'campaign_id' => 'getCampaignId',
        'campaign_name' => 'getCampaignName',
        'campaign_track_id' => 'getCampaignTrackId',
        'conversion_optimizer_eligibility' => 'getConversionOptimizerEligibility',
        'custom_parameters' => 'getCustomParameters',
        'end_date' => 'getEndDate',
        'failed_bidding_strategy_configuration' => 'getFailedBiddingStrategyConfiguration',
        'labels' => 'getLabels',
        'serving_status' => 'getServingStatus',
        'settings' => 'getSettings',
        'start_date' => 'getStartDate',
        'tracking_url' => 'getTrackingUrl',
        'type' => 'getType',
        'url_review_data' => 'getUrlReviewData',
        'user_status' => 'getUserStatus',
        'created_date' => 'getCreatedDate'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('account_id', $data ?? [], null);
        $this->setIfExists('app_id', $data ?? [], null);
        $this->setIfExists('app_store', $data ?? [], null);
        $this->setIfExists('bidding_strategy_configuration', $data ?? [], null);
        $this->setIfExists('bidding_strategy_failed_reason', $data ?? [], null);
        $this->setIfExists('budget', $data ?? [], null);
        $this->setIfExists('campaign_id', $data ?? [], null);
        $this->setIfExists('campaign_name', $data ?? [], null);
        $this->setIfExists('campaign_track_id', $data ?? [], null);
        $this->setIfExists('conversion_optimizer_eligibility', $data ?? [], null);
        $this->setIfExists('custom_parameters', $data ?? [], null);
        $this->setIfExists('end_date', $data ?? [], null);
        $this->setIfExists('failed_bidding_strategy_configuration', $data ?? [], null);
        $this->setIfExists('labels', $data ?? [], null);
        $this->setIfExists('serving_status', $data ?? [], null);
        $this->setIfExists('settings', $data ?? [], null);
        $this->setIfExists('start_date', $data ?? [], null);
        $this->setIfExists('tracking_url', $data ?? [], null);
        $this->setIfExists('type', $data ?? [], null);
        $this->setIfExists('url_review_data', $data ?? [], null);
        $this->setIfExists('user_status', $data ?? [], null);
        $this->setIfExists('created_date', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets account_id
     *
     * @return int|null
     */
    public function getAccountId()
    {
        return $this->container['account_id'];
    }

    /**
     * Sets account_id
     *
     * @param int|null $account_id <div lang=\"ja\">アカウントIDです。<br> このフィールドは、レスポンスの際に返却されますが、リクエストの際には無視されます。</div> <div lang=\"en\">Account ID.<br> Although this field will be returned in the response, it will be ignored on input.</div>
     *
     * @return self
     */
    public function setAccountId($account_id)
    {

        if (is_null($account_id)) {
            array_push($this->openAPINullablesSetToNull, 'account_id');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('account_id', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }

        $this->container['account_id'] = $account_id;

        return $this;
    }

    /**
     * Gets app_id
     *
     * @return string|null
     */
    public function getAppId()
    {
        return $this->container['app_id'];
    }

    /**
     * Sets app_id
     *
     * @param string|null $app_id <div lang=\"ja\">アプリID（iOS）またはパッケージ名（Android）です。<br> ※アプリキャンペーンでiOSの場合、入力は数値のみです。<br> ADD時、campaignTypeがSTANDARD、またはDYNAMIC_ADS_FOR_SEARCH_SETTINGの場合、無視され、MOBILE_APPの場合、必須となります。</div> <div lang=\"en\">App ID (for iOS) or Package name (for Android).<br> *Input only the numbers for iOS in Mobile App Campaign.<br>  In ADD operation, this field will be ignored when campaignType is 'STANDARD' or 'DYNAMIC_ADS_FOR_SEARCH_SETTING', and is required when campaignType is MOBILE_APP.</div>
     *
     * @return self
     */
    public function setAppId($app_id)
    {

        if (is_null($app_id)) {
            array_push($this->openAPINullablesSetToNull, 'app_id');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('app_id', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }

        $this->container['app_id'] = $app_id;

        return $this;
    }

    /**
     * Gets app_store
     *
     * @return \OpenAPI\Client\Model\CampaignServiceAppStore|null
     */
    public function getAppStore()
    {
        return $this->container['app_store'];
    }

    /**
     * Sets app_store
     *
     * @param \OpenAPI\Client\Model\CampaignServiceAppStore|null $app_store app_store
     *
     * @return self
     */
    public function setAppStore($app_store)
    {

        if (is_null($app_store)) {
            array_push($this->openAPINullablesSetToNull, 'app_store');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('app_store', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }

        $this->container['app_store'] = $app_store;

        return $this;
    }

    /**
     * Gets bidding_strategy_configuration
     *
     * @return \OpenAPI\Client\Model\CampaignServiceBiddingStrategy|null
     */
    public function getBiddingStrategyConfiguration()
    {
        return $this->container['bidding_strategy_configuration'];
    }

    /**
     * Sets bidding_strategy_configuration
     *
     * @param \OpenAPI\Client\Model\CampaignServiceBiddingStrategy|null $bidding_strategy_configuration bidding_strategy_configuration
     *
     * @return self
     */
    public function setBiddingStrategyConfiguration($bidding_strategy_configuration)
    {

        if (is_null($bidding_strategy_configuration)) {
            array_push($this->openAPINullablesSetToNull, 'bidding_strategy_configuration');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('bidding_strategy_configuration', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }

        $this->container['bidding_strategy_configuration'] = $bidding_strategy_configuration;

        return $this;
    }

    /**
     * Gets bidding_strategy_failed_reason
     *
     * @return \OpenAPI\Client\Model\CampaignServiceBiddingStrategyFailedReason|null
     */
    public function getBiddingStrategyFailedReason()
    {
        return $this->container['bidding_strategy_failed_reason'];
    }

    /**
     * Sets bidding_strategy_failed_reason
     *
     * @param \OpenAPI\Client\Model\CampaignServiceBiddingStrategyFailedReason|null $bidding_strategy_failed_reason bidding_strategy_failed_reason
     *
     * @return self
     */
    public function setBiddingStrategyFailedReason($bidding_strategy_failed_reason)
    {

        if (is_null($bidding_strategy_failed_reason)) {
            array_push($this->openAPINullablesSetToNull, 'bidding_strategy_failed_reason');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('bidding_strategy_failed_reason', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }

        $this->container['bidding_strategy_failed_reason'] = $bidding_strategy_failed_reason;

        return $this;
    }

    /**
     * Gets budget
     *
     * @return \OpenAPI\Client\Model\CampaignServiceBudget|null
     */
    public function getBudget()
    {
        return $this->container['budget'];
    }

    /**
     * Sets budget
     *
     * @param \OpenAPI\Client\Model\CampaignServiceBudget|null $budget budget
     *
     * @return self
     */
    public function setBudget($budget)
    {

        if (is_null($budget)) {
            array_push($this->openAPINullablesSetToNull, 'budget');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('budget', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }

        $this->container['budget'] = $budget;

        return $this;
    }

    /**
     * Gets campaign_id
     *
     * @return int|null
     */
    public function getCampaignId()
    {
        return $this->container['campaign_id'];
    }

    /**
     * Sets campaign_id
     *
     * @param int|null $campaign_id <div lang=\"ja\">キャンペーンIDです。<br> SET時およびREMOVE時、このフィールドは必須です。</div> <div lang=\"en\">Campaign ID.<br> This field is required in SET and REMOVE operation.</div>
     *
     * @return self
     */
    public function setCampaignId($campaign_id)
    {

        if (is_null($campaign_id)) {
            array_push($this->openAPINullablesSetToNull, 'campaign_id');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('campaign_id', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }

        $this->container['campaign_id'] = $campaign_id;

        return $this;
    }

    /**
     * Gets campaign_name
     *
     * @return string|null
     */
    public function getCampaignName()
    {
        return $this->container['campaign_name'];
    }

    /**
     * Sets campaign_name
     *
     * @param string|null $campaign_name <div lang=\"ja\">キャンペーン名です。<br>このフィールドは、ADD時に必須となり、SET時に省略可能となります。<br> ※入力制限：50文字以内です。</div> <div lang=\"en\">Campaign name.<br> *Insert limit: Up to 50 characters.<br>This field is required in ADD operation, and will be optional in SET operation.</div>
     *
     * @return self
     */
    public function setCampaignName($campaign_name)
    {

        if (is_null($campaign_name)) {
            array_push($this->openAPINullablesSetToNull, 'campaign_name');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('campaign_name', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }

        $this->container['campaign_name'] = $campaign_name;

        return $this;
    }

    /**
     * Gets campaign_track_id
     *
     * @return int|null
     */
    public function getCampaignTrackId()
    {
        return $this->container['campaign_track_id'];
    }

    /**
     * Sets campaign_track_id
     *
     * @param int|null $campaign_track_id <div lang=\"ja\">トラッキング用キャンペーンIDです。<br> このフィールドは、レスポンスの際に返却されますが、リクエストの際には無視されます。</div> <div lang=\"en\">Campaign ID for tracking.<br> Although this field will be returned in the response, it will be ignored on input.</div>
     *
     * @return self
     */
    public function setCampaignTrackId($campaign_track_id)
    {

        if (is_null($campaign_track_id)) {
            array_push($this->openAPINullablesSetToNull, 'campaign_track_id');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('campaign_track_id', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }

        $this->container['campaign_track_id'] = $campaign_track_id;

        return $this;
    }

    /**
     * Gets conversion_optimizer_eligibility
     *
     * @return \OpenAPI\Client\Model\CampaignServiceConversionOptimizerEligibility|null
     */
    public function getConversionOptimizerEligibility()
    {
        return $this->container['conversion_optimizer_eligibility'];
    }

    /**
     * Sets conversion_optimizer_eligibility
     *
     * @param \OpenAPI\Client\Model\CampaignServiceConversionOptimizerEligibility|null $conversion_optimizer_eligibility conversion_optimizer_eligibility
     *
     * @return self
     */
    public function setConversionOptimizerEligibility($conversion_optimizer_eligibility)
    {

        if (is_null($conversion_optimizer_eligibility)) {
            array_push($this->openAPINullablesSetToNull, 'conversion_optimizer_eligibility');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('conversion_optimizer_eligibility', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }

        $this->container['conversion_optimizer_eligibility'] = $conversion_optimizer_eligibility;

        return $this;
    }

    /**
     * Gets custom_parameters
     *
     * @return \OpenAPI\Client\Model\CampaignServiceCustomParameters|null
     */
    public function getCustomParameters()
    {
        return $this->container['custom_parameters'];
    }

    /**
     * Sets custom_parameters
     *
     * @param \OpenAPI\Client\Model\CampaignServiceCustomParameters|null $custom_parameters custom_parameters
     *
     * @return self
     */
    public function setCustomParameters($custom_parameters)
    {

        if (is_null($custom_parameters)) {
            array_push($this->openAPINullablesSetToNull, 'custom_parameters');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('custom_parameters', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }

        $this->container['custom_parameters'] = $custom_parameters;

        return $this;
    }

    /**
     * Gets end_date
     *
     * @return string|null
     */
    public function getEndDate()
    {
        return $this->container['end_date'];
    }

    /**
     * Sets end_date
     *
     * @param string|null $end_date <div lang=\"ja\">キャンペーンの終了日です。<br> ADD時およびSET時、このフィールドは省略可能となります。ADD時のデフォルト設定値は20371231となります。<br> 過去の日付、開始日以前の日付は指定できません。<br>※YYYYMMDD形式です。</div> <div lang=\"en\">End date of Campaign.<br> This field is optional in ADD and SET operation. The default value in ADD operation will be 20371231.<br> *Cannot set the past date and date before the start date.<br> *In YYYYMMDD format.</div>
     *
     * @return self
     */
    public function setEndDate($end_date)
    {

        if (is_null($end_date)) {
            array_push($this->openAPINullablesSetToNull, 'end_date');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('end_date', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }

        $this->container['end_date'] = $end_date;

        return $this;
    }

    /**
     * Gets failed_bidding_strategy_configuration
     *
     * @return \OpenAPI\Client\Model\CampaignServiceBiddingStrategy|null
     */
    public function getFailedBiddingStrategyConfiguration()
    {
        return $this->container['failed_bidding_strategy_configuration'];
    }

    /**
     * Sets failed_bidding_strategy_configuration
     *
     * @param \OpenAPI\Client\Model\CampaignServiceBiddingStrategy|null $failed_bidding_strategy_configuration failed_bidding_strategy_configuration
     *
     * @return self
     */
    public function setFailedBiddingStrategyConfiguration($failed_bidding_strategy_configuration)
    {

        if (is_null($failed_bidding_strategy_configuration)) {
            array_push($this->openAPINullablesSetToNull, 'failed_bidding_strategy_configuration');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('failed_bidding_strategy_configuration', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }

        $this->container['failed_bidding_strategy_configuration'] = $failed_bidding_strategy_configuration;

        return $this;
    }

    /**
     * Gets labels
     *
     * @return \OpenAPI\Client\Model\CampaignServiceLabel[]|null
     */
    public function getLabels()
    {
        return $this->container['labels'];
    }

    /**
     * Sets labels
     *
     * @param \OpenAPI\Client\Model\CampaignServiceLabel[]|null $labels labels
     *
     * @return self
     */
    public function setLabels($labels)
    {

        if (is_null($labels)) {
            array_push($this->openAPINullablesSetToNull, 'labels');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('labels', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }

        $this->container['labels'] = $labels;

        return $this;
    }

    /**
     * Gets serving_status
     *
     * @return \OpenAPI\Client\Model\CampaignServiceServingStatus|null
     */
    public function getServingStatus()
    {
        return $this->container['serving_status'];
    }

    /**
     * Sets serving_status
     *
     * @param \OpenAPI\Client\Model\CampaignServiceServingStatus|null $serving_status serving_status
     *
     * @return self
     */
    public function setServingStatus($serving_status)
    {

        if (is_null($serving_status)) {
            array_push($this->openAPINullablesSetToNull, 'serving_status');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('serving_status', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }

        $this->container['serving_status'] = $serving_status;

        return $this;
    }

    /**
     * Gets settings
     *
     * @return \OpenAPI\Client\Model\CampaignServiceSettings[]|null
     */
    public function getSettings()
    {
        return $this->container['settings'];
    }

    /**
     * Sets settings
     *
     * @param \OpenAPI\Client\Model\CampaignServiceSettings[]|null $settings settings
     *
     * @return self
     */
    public function setSettings($settings)
    {

        if (is_null($settings)) {
            array_push($this->openAPINullablesSetToNull, 'settings');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('settings', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }

        $this->container['settings'] = $settings;

        return $this;
    }

    /**
     * Gets start_date
     *
     * @return string|null
     */
    public function getStartDate()
    {
        return $this->container['start_date'];
    }

    /**
     * Sets start_date
     *
     * @param string|null $start_date <div lang=\"ja\">キャンペーンの開始日です。<br> ADD時およびSET時、このフィールドは省略可能となります。ADD時のデフォルト設定値は当日日付となります。<br> 過去の日付は指定できません。<br>※配信開始済みのキャンペーンは変更できません。<br> ※YYYYMMDD形式です。</div> <div lang=\"en\">Start date of Campaign.<br> This field is optional in ADD and SET operation. The default value in ADD operation will be Today's date.<br> *Cannot set the past date.<br>*Cannot change the date to the campaign that is already active.<br> *In YYYYMMDD format.</div>
     *
     * @return self
     */
    public function setStartDate($start_date)
    {

        if (is_null($start_date)) {
            array_push($this->openAPINullablesSetToNull, 'start_date');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('start_date', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }

        $this->container['start_date'] = $start_date;

        return $this;
    }

    /**
     * Gets tracking_url
     *
     * @return string|null
     */
    public function getTrackingUrl()
    {
        return $this->container['tracking_url'];
    }

    /**
     * Sets tracking_url
     *
     * @param string|null $tracking_url <div lang=\"ja\">トラッキングURLです。<br> ADD時およびSET時、このフィールドは省略可能となります。<br> ※アプリキャンペーンがAndroidの場合、設定はできません。</div> <div lang=\"en\">Tracking URL.<br> This field is optional in ADD and SET operation.<br> *Cannot set if Mobile App Campaign is in Android.</div>
     *
     * @return self
     */
    public function setTrackingUrl($tracking_url)
    {

        if (is_null($tracking_url)) {
            array_push($this->openAPINullablesSetToNull, 'tracking_url');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('tracking_url', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }

        $this->container['tracking_url'] = $tracking_url;

        return $this;
    }

    /**
     * Gets type
     *
     * @return \OpenAPI\Client\Model\CampaignServiceType|null
     */
    public function getType()
    {
        return $this->container['type'];
    }

    /**
     * Sets type
     *
     * @param \OpenAPI\Client\Model\CampaignServiceType|null $type type
     *
     * @return self
     */
    public function setType($type)
    {

        if (is_null($type)) {
            array_push($this->openAPINullablesSetToNull, 'type');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('type', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }

        $this->container['type'] = $type;

        return $this;
    }

    /**
     * Gets url_review_data
     *
     * @return \OpenAPI\Client\Model\CampaignServiceUrlReviewData|null
     */
    public function getUrlReviewData()
    {
        return $this->container['url_review_data'];
    }

    /**
     * Sets url_review_data
     *
     * @param \OpenAPI\Client\Model\CampaignServiceUrlReviewData|null $url_review_data url_review_data
     *
     * @return self
     */
    public function setUrlReviewData($url_review_data)
    {

        if (is_null($url_review_data)) {
            array_push($this->openAPINullablesSetToNull, 'url_review_data');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('url_review_data', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }

        $this->container['url_review_data'] = $url_review_data;

        return $this;
    }

    /**
     * Gets user_status
     *
     * @return \OpenAPI\Client\Model\CampaignServiceUserStatus|null
     */
    public function getUserStatus()
    {
        return $this->container['user_status'];
    }

    /**
     * Sets user_status
     *
     * @param \OpenAPI\Client\Model\CampaignServiceUserStatus|null $user_status user_status
     *
     * @return self
     */
    public function setUserStatus($user_status)
    {

        if (is_null($user_status)) {
            array_push($this->openAPINullablesSetToNull, 'user_status');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('user_status', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }

        $this->container['user_status'] = $user_status;

        return $this;
    }

    /**
     * Gets created_date
     *
     * @return string|null
     */
    public function getCreatedDate()
    {
        return $this->container['created_date'];
    }

    /**
     * Sets created_date
     *
     * @param string|null $created_date <div lang=\"ja\">キャンペーンが作成された日です。<br>※フォーマット：yyyyMMdd</div> <div lang=\"en\">Date of Campaign made.<br>* Format: yyyyMMdd</div>
     *
     * @return self
     */
    public function setCreatedDate($created_date)
    {

        if (is_null($created_date)) {
            array_push($this->openAPINullablesSetToNull, 'created_date');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('created_date', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }

        $this->container['created_date'] = $created_date;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


