<?php
/**
 * AdGroupCriterionServiceApi
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Yahoo!広告 検索広告 API リファレンス / Yahoo! JAPAN Ads Search Ads API Reference
 *
 * <div lang=\"ja\">Yahoo!広告 検索広告 APIのWebサービスについて説明します。</div> <div lang=\"en\">Search Ads API Web Services supported in Yahoo! JAPAN Ads API.</div> <div><a target=\"_blank\" href=\"https://github.com/yahoojp-marketing/ads-search-api-documents/blob/master/design/v9/Route.yaml\">OpenAPI Specification</a></div> <div lang=\"ja\"><a target=\"_blank\" href=\"https://github.com/yahoojp-marketing/ads-search-api-documents/blob/master/bestpractice/ja\">Best Practice</a></div> <div lang=\"en\"><a target=\"_blank\" href=\"https://github.com/yahoojp-marketing/ads-search-api-documents/blob/master/bestpractice/en\">Best Practice</a></div>
 *
 * The version of the OpenAPI document: v9
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.2.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use OpenAPI\Client\ApiException;
use OpenAPI\Client\Configuration;
use OpenAPI\Client\HeaderSelector;
use OpenAPI\Client\ObjectSerializer;

/**
 * AdGroupCriterionServiceApi Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class AdGroupCriterionServiceApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /** @var string[] $contentTypes **/
    public const contentTypes = [
        'adGroupCriterionServiceAddPost' => [
            'application/json',
        ],
        'adGroupCriterionServiceGetPost' => [
            'application/json',
        ],
        'adGroupCriterionServiceRemovePost' => [
            'application/json',
        ],
        'adGroupCriterionServiceSetPost' => [
            'application/json',
        ],
    ];

/**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ClientInterface $client = null,
        Configuration $config = null,
        HeaderSelector $selector = null,
        $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: new Configuration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation adGroupCriterionServiceAddPost
     *
     * @param  \OpenAPI\Client\Model\AdGroupCriterionServiceOperation $ad_group_criterion_service_operation ad_group_criterion_service_operation (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['adGroupCriterionServiceAddPost'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return |\OpenAPI\Client\Model\AdGroupCriterionServiceMutateResponse
     */
    public function adGroupCriterionServiceAddPost($ad_group_criterion_service_operation = null, string $contentType = self::contentTypes['adGroupCriterionServiceAddPost'][0])
    {
        list($response) = $this->adGroupCriterionServiceAddPostWithHttpInfo($ad_group_criterion_service_operation, $contentType);
        return $response;
    }

    /**
     * Operation adGroupCriterionServiceAddPostWithHttpInfo
     *
     * @param  \OpenAPI\Client\Model\AdGroupCriterionServiceOperation $ad_group_criterion_service_operation (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['adGroupCriterionServiceAddPost'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of |\OpenAPI\Client\Model\AdGroupCriterionServiceMutateResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function adGroupCriterionServiceAddPostWithHttpInfo($ad_group_criterion_service_operation = null, string $contentType = self::contentTypes['adGroupCriterionServiceAddPost'][0])
    {
        $request = $this->adGroupCriterionServiceAddPostRequest($ad_group_criterion_service_operation, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 200:
                    if ('\OpenAPI\Client\Model\AdGroupCriterionServiceMutateResponse' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\OpenAPI\Client\Model\AdGroupCriterionServiceMutateResponse' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\OpenAPI\Client\Model\AdGroupCriterionServiceMutateResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\OpenAPI\Client\Model\AdGroupCriterionServiceMutateResponse';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\AdGroupCriterionServiceMutateResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation adGroupCriterionServiceAddPostAsync
     *
     * @param  \OpenAPI\Client\Model\AdGroupCriterionServiceOperation $ad_group_criterion_service_operation (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['adGroupCriterionServiceAddPost'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function adGroupCriterionServiceAddPostAsync($ad_group_criterion_service_operation = null, string $contentType = self::contentTypes['adGroupCriterionServiceAddPost'][0])
    {
        return $this->adGroupCriterionServiceAddPostAsyncWithHttpInfo($ad_group_criterion_service_operation, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation adGroupCriterionServiceAddPostAsyncWithHttpInfo
     *
     * @param  \OpenAPI\Client\Model\AdGroupCriterionServiceOperation $ad_group_criterion_service_operation (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['adGroupCriterionServiceAddPost'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function adGroupCriterionServiceAddPostAsyncWithHttpInfo($ad_group_criterion_service_operation = null, string $contentType = self::contentTypes['adGroupCriterionServiceAddPost'][0])
    {
        $returnType = '\OpenAPI\Client\Model\AdGroupCriterionServiceMutateResponse';
        $request = $this->adGroupCriterionServiceAddPostRequest($ad_group_criterion_service_operation, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'adGroupCriterionServiceAddPost'
     *
     * @param  \OpenAPI\Client\Model\AdGroupCriterionServiceOperation $ad_group_criterion_service_operation (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['adGroupCriterionServiceAddPost'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function adGroupCriterionServiceAddPostRequest($ad_group_criterion_service_operation = null, string $contentType = self::contentTypes['adGroupCriterionServiceAddPost'][0])
    {



        $resourcePath = '/AdGroupCriterionService/add';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;





        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($ad_group_criterion_service_operation)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($ad_group_criterion_service_operation));
            } else {
                $httpBody = $ad_group_criterion_service_operation;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\json_encode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires OAuth (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation adGroupCriterionServiceGetPost
     *
     * @param  \OpenAPI\Client\Model\AdGroupCriterionServiceSelector $ad_group_criterion_service_selector ad_group_criterion_service_selector (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['adGroupCriterionServiceGetPost'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return |\OpenAPI\Client\Model\AdGroupCriterionServiceGetResponse
     */
    public function adGroupCriterionServiceGetPost($ad_group_criterion_service_selector = null, string $contentType = self::contentTypes['adGroupCriterionServiceGetPost'][0])
    {
        list($response) = $this->adGroupCriterionServiceGetPostWithHttpInfo($ad_group_criterion_service_selector, $contentType);
        return $response;
    }

    /**
     * Operation adGroupCriterionServiceGetPostWithHttpInfo
     *
     * @param  \OpenAPI\Client\Model\AdGroupCriterionServiceSelector $ad_group_criterion_service_selector (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['adGroupCriterionServiceGetPost'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of |\OpenAPI\Client\Model\AdGroupCriterionServiceGetResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function adGroupCriterionServiceGetPostWithHttpInfo($ad_group_criterion_service_selector = null, string $contentType = self::contentTypes['adGroupCriterionServiceGetPost'][0])
    {
        $request = $this->adGroupCriterionServiceGetPostRequest($ad_group_criterion_service_selector, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 200:
                    if ('\OpenAPI\Client\Model\AdGroupCriterionServiceGetResponse' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\OpenAPI\Client\Model\AdGroupCriterionServiceGetResponse' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\OpenAPI\Client\Model\AdGroupCriterionServiceGetResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\OpenAPI\Client\Model\AdGroupCriterionServiceGetResponse';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\AdGroupCriterionServiceGetResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation adGroupCriterionServiceGetPostAsync
     *
     * @param  \OpenAPI\Client\Model\AdGroupCriterionServiceSelector $ad_group_criterion_service_selector (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['adGroupCriterionServiceGetPost'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function adGroupCriterionServiceGetPostAsync($ad_group_criterion_service_selector = null, string $contentType = self::contentTypes['adGroupCriterionServiceGetPost'][0])
    {
        return $this->adGroupCriterionServiceGetPostAsyncWithHttpInfo($ad_group_criterion_service_selector, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation adGroupCriterionServiceGetPostAsyncWithHttpInfo
     *
     * @param  \OpenAPI\Client\Model\AdGroupCriterionServiceSelector $ad_group_criterion_service_selector (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['adGroupCriterionServiceGetPost'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function adGroupCriterionServiceGetPostAsyncWithHttpInfo($ad_group_criterion_service_selector = null, string $contentType = self::contentTypes['adGroupCriterionServiceGetPost'][0])
    {
        $returnType = '\OpenAPI\Client\Model\AdGroupCriterionServiceGetResponse';
        $request = $this->adGroupCriterionServiceGetPostRequest($ad_group_criterion_service_selector, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'adGroupCriterionServiceGetPost'
     *
     * @param  \OpenAPI\Client\Model\AdGroupCriterionServiceSelector $ad_group_criterion_service_selector (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['adGroupCriterionServiceGetPost'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function adGroupCriterionServiceGetPostRequest($ad_group_criterion_service_selector = null, string $contentType = self::contentTypes['adGroupCriterionServiceGetPost'][0])
    {



        $resourcePath = '/AdGroupCriterionService/get';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;





        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($ad_group_criterion_service_selector)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($ad_group_criterion_service_selector));
            } else {
                $httpBody = $ad_group_criterion_service_selector;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\json_encode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires OAuth (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation adGroupCriterionServiceRemovePost
     *
     * @param  \OpenAPI\Client\Model\AdGroupCriterionServiceOperation $ad_group_criterion_service_operation ad_group_criterion_service_operation (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['adGroupCriterionServiceRemovePost'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return |\OpenAPI\Client\Model\AdGroupCriterionServiceMutateResponse
     */
    public function adGroupCriterionServiceRemovePost($ad_group_criterion_service_operation = null, string $contentType = self::contentTypes['adGroupCriterionServiceRemovePost'][0])
    {
        list($response) = $this->adGroupCriterionServiceRemovePostWithHttpInfo($ad_group_criterion_service_operation, $contentType);
        return $response;
    }

    /**
     * Operation adGroupCriterionServiceRemovePostWithHttpInfo
     *
     * @param  \OpenAPI\Client\Model\AdGroupCriterionServiceOperation $ad_group_criterion_service_operation (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['adGroupCriterionServiceRemovePost'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of |\OpenAPI\Client\Model\AdGroupCriterionServiceMutateResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function adGroupCriterionServiceRemovePostWithHttpInfo($ad_group_criterion_service_operation = null, string $contentType = self::contentTypes['adGroupCriterionServiceRemovePost'][0])
    {
        $request = $this->adGroupCriterionServiceRemovePostRequest($ad_group_criterion_service_operation, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 200:
                    if ('\OpenAPI\Client\Model\AdGroupCriterionServiceMutateResponse' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\OpenAPI\Client\Model\AdGroupCriterionServiceMutateResponse' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\OpenAPI\Client\Model\AdGroupCriterionServiceMutateResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\OpenAPI\Client\Model\AdGroupCriterionServiceMutateResponse';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\AdGroupCriterionServiceMutateResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation adGroupCriterionServiceRemovePostAsync
     *
     * @param  \OpenAPI\Client\Model\AdGroupCriterionServiceOperation $ad_group_criterion_service_operation (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['adGroupCriterionServiceRemovePost'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function adGroupCriterionServiceRemovePostAsync($ad_group_criterion_service_operation = null, string $contentType = self::contentTypes['adGroupCriterionServiceRemovePost'][0])
    {
        return $this->adGroupCriterionServiceRemovePostAsyncWithHttpInfo($ad_group_criterion_service_operation, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation adGroupCriterionServiceRemovePostAsyncWithHttpInfo
     *
     * @param  \OpenAPI\Client\Model\AdGroupCriterionServiceOperation $ad_group_criterion_service_operation (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['adGroupCriterionServiceRemovePost'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function adGroupCriterionServiceRemovePostAsyncWithHttpInfo($ad_group_criterion_service_operation = null, string $contentType = self::contentTypes['adGroupCriterionServiceRemovePost'][0])
    {
        $returnType = '\OpenAPI\Client\Model\AdGroupCriterionServiceMutateResponse';
        $request = $this->adGroupCriterionServiceRemovePostRequest($ad_group_criterion_service_operation, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'adGroupCriterionServiceRemovePost'
     *
     * @param  \OpenAPI\Client\Model\AdGroupCriterionServiceOperation $ad_group_criterion_service_operation (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['adGroupCriterionServiceRemovePost'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function adGroupCriterionServiceRemovePostRequest($ad_group_criterion_service_operation = null, string $contentType = self::contentTypes['adGroupCriterionServiceRemovePost'][0])
    {



        $resourcePath = '/AdGroupCriterionService/remove';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;





        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($ad_group_criterion_service_operation)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($ad_group_criterion_service_operation));
            } else {
                $httpBody = $ad_group_criterion_service_operation;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\json_encode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires OAuth (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation adGroupCriterionServiceSetPost
     *
     * @param  \OpenAPI\Client\Model\AdGroupCriterionServiceOperation $ad_group_criterion_service_operation ad_group_criterion_service_operation (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['adGroupCriterionServiceSetPost'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return |\OpenAPI\Client\Model\AdGroupCriterionServiceMutateResponse
     */
    public function adGroupCriterionServiceSetPost($ad_group_criterion_service_operation = null, string $contentType = self::contentTypes['adGroupCriterionServiceSetPost'][0])
    {
        list($response) = $this->adGroupCriterionServiceSetPostWithHttpInfo($ad_group_criterion_service_operation, $contentType);
        return $response;
    }

    /**
     * Operation adGroupCriterionServiceSetPostWithHttpInfo
     *
     * @param  \OpenAPI\Client\Model\AdGroupCriterionServiceOperation $ad_group_criterion_service_operation (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['adGroupCriterionServiceSetPost'] to see the possible values for this operation
     *
     * @throws \OpenAPI\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of |\OpenAPI\Client\Model\AdGroupCriterionServiceMutateResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function adGroupCriterionServiceSetPostWithHttpInfo($ad_group_criterion_service_operation = null, string $contentType = self::contentTypes['adGroupCriterionServiceSetPost'][0])
    {
        $request = $this->adGroupCriterionServiceSetPostRequest($ad_group_criterion_service_operation, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 200:
                    if ('\OpenAPI\Client\Model\AdGroupCriterionServiceMutateResponse' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\OpenAPI\Client\Model\AdGroupCriterionServiceMutateResponse' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\OpenAPI\Client\Model\AdGroupCriterionServiceMutateResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\OpenAPI\Client\Model\AdGroupCriterionServiceMutateResponse';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OpenAPI\Client\Model\AdGroupCriterionServiceMutateResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation adGroupCriterionServiceSetPostAsync
     *
     * @param  \OpenAPI\Client\Model\AdGroupCriterionServiceOperation $ad_group_criterion_service_operation (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['adGroupCriterionServiceSetPost'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function adGroupCriterionServiceSetPostAsync($ad_group_criterion_service_operation = null, string $contentType = self::contentTypes['adGroupCriterionServiceSetPost'][0])
    {
        return $this->adGroupCriterionServiceSetPostAsyncWithHttpInfo($ad_group_criterion_service_operation, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation adGroupCriterionServiceSetPostAsyncWithHttpInfo
     *
     * @param  \OpenAPI\Client\Model\AdGroupCriterionServiceOperation $ad_group_criterion_service_operation (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['adGroupCriterionServiceSetPost'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function adGroupCriterionServiceSetPostAsyncWithHttpInfo($ad_group_criterion_service_operation = null, string $contentType = self::contentTypes['adGroupCriterionServiceSetPost'][0])
    {
        $returnType = '\OpenAPI\Client\Model\AdGroupCriterionServiceMutateResponse';
        $request = $this->adGroupCriterionServiceSetPostRequest($ad_group_criterion_service_operation, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'adGroupCriterionServiceSetPost'
     *
     * @param  \OpenAPI\Client\Model\AdGroupCriterionServiceOperation $ad_group_criterion_service_operation (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['adGroupCriterionServiceSetPost'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function adGroupCriterionServiceSetPostRequest($ad_group_criterion_service_operation = null, string $contentType = self::contentTypes['adGroupCriterionServiceSetPost'][0])
    {



        $resourcePath = '/AdGroupCriterionService/set';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;





        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($ad_group_criterion_service_operation)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($ad_group_criterion_service_operation));
            } else {
                $httpBody = $ad_group_criterion_service_operation;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\json_encode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires OAuth (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }
}
